language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: AIla+lbTSG/Myco6eIAiLgRggZYEF5LVmn5/1K0CVy48l7NDGChZJNxa6b2+YK5sVpw3G9lCmY39g5ZUMeC/lrld7b1NRNOnpafuTVD0KMv0/AFglVPjG2MmruZnrzT9i7IPu58rxGm8mcoWulVJjJd0SfsT82lGlYszkgYLpa5PSeUrsFVZWS+dvPWevU9DfFKvt9wx9+sOgc68WErF+YaT4oA4JY3ikUyQJndQMy9E8OewPklF7XtW/yk6qhPrss5M9pBqoMoQXI4y0C36e6fU5a6F7jlH43Dxtzy8NLHm/tTxzvMMNaAbF3JE8VcXA42AQG8qHK5KwI2n/mprpfLj4YR8AJ1ztiaFdN2dyi2WtU8uoCaLaha/19tt/gPT901K+/IEdAfXMbYW22QTEvBlZ6iZmlvf3UoMZBIBUlodtkupwC3F8l8Cg1S/vCg1gEW1NJj/kYFYY7rTPVU9Fdnesk53pM/0QXPBdJHwEFwR00mEzs8VNT1vUIX8XVzSCrOZ6nMMflFiQbehD7DLDFPHAjHNfvXvKblkBq+YKP10pFG/nOQrebEy8qj6NjdP10LhncPMZXk+Is9GsGFNXu6XX1s1MlN9XlhTOA1nh3W5rF3QkdqQ1HYQXFdXvgmOy0FZK3kiMHJfwr9hM7l0qteFT0ANnCXmJhUdAHUjSMc=
